Screenful.Loc={
  ready: "준비되었습니다.",
  find: "검색",
  reload: "새로고침",
  cancel: "취소",
  more: "더 보기",
  new: "새 항목",
  edit: "편집",
  save: "저장",
  delete: "삭제",
  listing: "목록을 불러오는 중...",
  listingFailed: "목록을 불러오지 못했습니다.",
  reading: "항목을 불러오는 중...",
  readingFailed: "해당 항목이 없습니다.",
  saving: "저장 중...",
  savingFailed: "저장하지 못했습니다.",
  deleting: "삭제 중...",
  deletingFailed: "삭제하지 못했습니다.",
  deleteConfirm: "정말 삭제하시겠습니까?",
  username: "전자 우편 주소",
  password: "비밀번호",
  login: "계정 들어가기",
  loginError: "전자 우편 주소 또는 비밀번호가 올바르지 않습니다.",
  logout: "계정 나가기",
  anonymous: "익명 사용자",
  home: "홈",
  title: "제목",
  titleEmpty: "제목을 입력하세요.",
  url: "URL",
  urlEmpty: "URL을 입력하세요.",
  urlShort: "URL은 3자 이상이어야 합니다.",
  urlInvalid: "URL에는 영문자(a-z, A-Z), 숫자(0-9), 하이픈(-)만 사용할 수 있습니다.",
  urlTaken: "이미 사용 중인 URL입니다.",
  template: "템플릿",
  create: "만들기",
  finished: "완료",
  changePwd: "비밀번호 변경",
  signup: "회원 가입",
  forgotPwd: "비밀번호를 잊으셨나요?",
  signupEmail: "계정을 만들려면 다음 주소로 이메일을 보내세요:",
  newPassword: "새 비밀번호",
  change: "변경",
  passwordChanged: "비밀번호가 변경되었습니다.",
  passwordEmpty: "비밀번호를 입력하세요.",
  passwordShort: "비밀번호는 6자 이상이어야 합니다.",
  passwordWhitespace: "비밀번호의 처음이나 끝에 공백을 사용할 수 없습니다.",
  ok: "확인",
  currentUrl: "현재 URL",
  newUrl: "새 URL",
  upload: "올려넣기",
  uploadPurge: "올려넣기 전에 기존 항목 삭제",
  uploadFail: "올려넣지 못했습니다.",
  uploadSuccess: "올려넣었습니다.",
  history: "변경 이력",
  version: "판본",
  clone: "복제",
  sourceCode: "소스 코드",
  invalidSourceCode: "올바르지 않은 소스 코드입니다.",
  unsavedConfirm: "저장하지 않은 변경사항이 있습니다. 변경사항을 버리시겠습니까?",
  doItLater: "나중에 하기",
  badEmailError: "전자 우편 주소가 올바르지 않습니다.",
  forgotPwdEmail: "비밀번호를 잊으셨다면 전자 우편 주소를 입력하세요. 새 비밀번호를 설정하는 방법을 이메일로 보내 드립니다.",
  recoverPwd: "비밀번호 재설정",
  tokenSent: "비밀번호 재설정 안내를 이메일로 보냈습니다.",
  recoverPwdMsg: "이제 비밀번호를 변경할 수 있습니다.",
  changePwdMsg: "여기에서 비밀번호를 변경할 수 있습니다.",
  invalidToken: "유효하지 않은 비밀번호 재설정 링크입니다. 만료되었거나 이미 사용된 링크일 수 있습니다.",
  signupInfoEmail: "새 계정을 만들려면 전자 우편 주소를 입력하세요. 가입 방법을 전자 우편으로 보내 드립니다.",
  signupButton: "새 계정 만들기",
  signupTokenSent: "계정 생성 안내를 전자 우편으로 보냈습니다.",
  invalidSignupToken: "유효하지 않은 가입 링크입니다. 만료되었거나 이미 사용된 링크일 수 있습니다.",
  setPwdMsg: "비밀번호를 설정하세요.",
  accountCreated: "계정이 생성되었습니다. 이제 전자 우편 주소와 비밀번호로 계정에 들어갈 수 있습니다.",
  autosave: "자동 저장",
  flagging: "표시 중...",
  flaggingFailed: "항목을 표시하지 못했습니다.",
  exactMatches: "완전 일치",
  partialMatches: "부분 일치",
  comments: "댓글",
  newComment: "새 댓글",
  revive: "복원",
  addToWorklist: "작업 목록에 추가",
  worklist: "작업 목록",
  action: "작업",
  purgeWorklist: "작업 목록에서 모두 제거",
  extranet: "엑스트라넷",
  doingBatch: "일괄 편집 중...",
  batchFailed: "일괄 편집하지 못했습니다.",
  printable: "인쇄용 보기",
  printableOff: "돌아가기",
  batchConfirm: "주의! 여기에 나열된 모든 항목(총 $X개)에 이 변경사항이 적용됩니다. 계속하시겠습니까?",
  narrow: "좁은 화면",
  narrowList: "목록",
  narrowEditor: "열람/편집",
  emailInUseError: "이미 사용 중인 전자 우편 주소입니다.",
  perPage: "페이지당 항목 수",
};
