function L(s, gloss){
  if(s=="only") return function(s){
    return s+"만";
  };
  if(s=="READ-ONLY") return "읽기 전용";
  if(s=="Editing") return "편집";
  if(s=="Dublin City University") return "더블린시티대학교";
  if(s=="Log out") return "계정 나가기";
  if(s=="Change your password") return "비밀번호 변경";
  if(s=="Registered user login") return "등록된 계정으로 들어가기";
  if(s=="Get an account") return "회원 가입";
  if(s=="Forgot your password?") return "비밀번호를 잊으셨나요?";
  if(s=="E-mail address") return "전자 우편 주소";
  if(s=="Password") return "비밀번호";
  if(s=="Log in") return "계정 들어가기";
  if(s=="Your termbases") return "내 용어집";
  if(s=="You have no termbases yet.") return "아직 용어집이 없습니다.";
  if(s=="Create a termbase") return "새 용어집 만들기";
  if(s=="Administration") return "관리";
  if(s=="Users") return "사용자";
  if(s=="Termbases") return "용어집";
  if(s=="smart search") return "스마트 검색";
  if(s=="complete term") return "용어 전체 일치";
  if(s=="start of term") return "용어의 시작 부분";
  if(s=="end of term") return "용어의 끝부분";
  if(s=="any part of term") return "용어의 어느 부분이든";
  if(s=="any part except start or end") return "시작과 끝을 제외한 부분";
  if(s=="search in all languages") return "모든 언어에서 검색";
  if(s=="Configuration") return "설정";
  if(s=="ADMIN") return "관리";
  if(s=="TRM") return "용어";
  if(s=="DOM") return "분야";
  if(s=="DEF") return "정의";
  if(s=="XMPL") return "용례";
  if(s=="CHECKING STATUS") return "검토 상태";
  if(s=="PUBLISHING STATUS") return "공개 상태";
  if(s=="TERMS") return "용어";
  if(s=="DOMAINS") return "분야";
  if(s=="term") return "용어";
  if(s=="clarification") return "보충 설명";
  if(s=="acceptability") return "사용 적합성";
  if(s=="source") return "출처";
  if(s=="inflected form") return "굴절형";
  if(s=="annotation") return "주석";
  if(s=="domain") return "분야";
  if(s=="part of speech") return "품사";
  if(s=="inflection") return "굴절";
  if(s=="language of origin") return "원어";
  if(s=="symbol") return "기호";
  if(s=="trademark") return "상표";
  if(s=="registered trademark") return "등록 상표";
  if(s=="proper noun") return "고유 명사";
  if(s=="formatting") return "서식";
  if(s=="italic") return "기울임꼴";
  if(s=="Created") return "생성됨";
  if(s=="Changed") return "변경됨";
  if(s=="Deleted") return "삭제됨";
  if(s=="Bulk-deleted") return "일괄 삭제됨";
  if(s=="while uploading") return "올려넣기 중";
  if(s=="By") return "작업자";
  if(s=="When") return "일시";
  if(s=="any checking status") return "모든 검토 상태";
  if(s=="any publishing status") return "모든 공개 상태";
  if(s=="any language") return "모든 언어";
  if(s=="any acceptability or no acceptability") return "사용 적합성 지정 여부 무관";
  if(s=="any acceptability") return "사용 적합성이 지정됨";
  if(s=="no acceptability") return "사용 적합성이 지정되지 않음";
  if(s=="any domain or no domain") return "분야 지정 여부 무관";
  if(s=="any domain") return "분야가 지정됨";
  if(s=="no domain") return "분야가 지정되지 않음";
  if(s=="LAST MAJOR UPDATE") return "최근 주요 갱신일";
  if(s=="set to today") return "오늘로 설정";
  if(s=="Invalid e-mail address or password.") return "전자 우편 주소 또는 비밀번호가 올바르지 않습니다.";
  if(s=="INTR") return "개요";
  if(s=="COLL") return "모음";
  if(s=="INTROS") return "개요";
  if(s=="DEFINITIONS") return "정의";
  if(s=="EXAMPLES") return "용례";
  if(s=="COLLECTIONS") return "모음";
  if(s=="definition") return "정의";
  if(s=="example") return "용례";
  if(s=="sentence") return "문장";
  if(s=="collection") return "모음";
  if(s=="any collection or no collection") return "모음 포함 여부 무관";
  if(s=="any collection") return "모음에 포함됨";
  if(s=="no collection") return "모음에 포함되지 않음";
  if(s=="comments") return "댓글";
  if(s=="with or without comments") return "댓글 유무 무관";
  if(s=="with comments") return "댓글 있음";
  if(s=="without comments") return "댓글 없음";
  if(s=="my comments") return "내 댓글";
  if(s=="with or without my comments") return "내 댓글 유무 무관";
  if(s=="with my comments") return "내 댓글 있음";
  if(s=="without my comments") return "내 댓글 없음";
  if(s=="other people's comments") return "다른 사용자의 댓글";
  if(s=="with or without other people's comments") return "다른 사용자의 댓글 유무 무관";
  if(s=="with other people's comments") return "다른 사용자의 댓글 있음";
  if(s=="without other people's comments") return "다른 사용자의 댓글 없음";
  if(s=="EXTRANET") return "엑스트라넷";
  if(s=="EXT") return "외부";
  if(s=="EXTRANETS") return "엑스트라넷";
  if(s=="extranet") return "엑스트라넷";
  if(s=="any extranet or no extranet") return "엑스트라넷 포함 여부 무관";
  if(s=="any extranet") return "엑스트라넷에 포함됨";
  if(s=="no extranet") return "엑스트라넷에 포함되지 않음";
  if(s=="sorting language") return "정렬 기준 언어";
  if(s=="Create mutual cross-references") return "상호 참조 만들기";
  if(s=="Remove mutual cross-references") return "상호 참조 제거";
  if(s=="Merge into a single entry") return "하나의 항목으로 병합";
  if(s=="SEE ALSO") return "함께 보기";
  if(s=="add to worklist") return "작업 목록에 추가";
  if(s=="Domains") return "분야";
  if(s=="Part-of-speech labels") return "품사 레이블";
  if(s=="Inflection labels") return "굴절 레이블";
  if(s=="Acceptability labels") return "사용 적합성 레이블";
  if(s=="Sources") return "출처";
  if(s=="Collections") return "모음";
  if(s=="Tags") return "태그";
  if(s=="Extranets") return "엑스트라넷";
  if(s=="Name and blurb") return "이름과 소개";
  if(s=="Features") return "기능";
  if(s=="Languages") return "언어";
  if(s=="Publishing") return "공개";
  if(s=="Change the termbase's URL") return "용어집 URL 변경";
  if(s=="Delete the termbase") return "용어집 삭제";
  if(s=="TITLE") return "제목";
  if(s=="abbreviation") return "약어";
  if(s=="LANGUAGES") return "언어";
  if(s=="select all") return "모두 선택";
  if(s=="unselect all") return "모두 선택 해제";
  if(s=="PRIORITY") return "우선순위";
  if(s=="high") return "높음";
  if(s=="medium") return "보통";
  if(s=="low") return "낮음";
  if(s=="USERS") return "사용자";
  if(s=="e-mail address") return "전자 우편 주소";
  if(s=="user") return "사용자";
  if(s=="Alphabetical order") return "문자순";
  if(s=="Similar terms (click to insert)") return "유사한 용어 (클릭하여 삽입)";
  if(s=="Other entries that share this term") return "이 용어를 공유하는 다른 항목";
  if(s=="stop sharing") return "공유 해제";
  if(s=="Change checking status to") return "검토 상태 변경";
  if(s=="Change publishing status to") return "공개 상태 변경";
  if(s=="Add to extranet") return "엑스트라넷에 추가";
  if(s=="Remove from extranet") return "엑스트라넷에서 제거";
  if(s=="checked") return "검토 완료";
  if(s=="not checked") return "미검토";
  if(s=="publishable") return "공개 가능";
  if(s=="hidden") return "숨김";
  if(s=="CHECKED") return "검토 완료";
  if(s=="NOT CHECKED") return "미검토";
  if(s=="PUBLISHABLE") return "공개 가능";
  if(s=="HIDDEN") return "숨김";
  if(s=="non-essential") return "필수 아님";
  if(s=="STATUS") return "상태";
  if(s=="live") return "활성";
  if(s=="not live") return "비활성";
  if(s=="any clarification or no clarification") return "보충 설명 유무 무관";
  if(s=="any clarification") return "보충 설명 있음";
  if(s=="no clarification") return "보충 설명 없음";
  if(s=="clarification containing...") return "보충 설명에 다음 내용 포함...";
  if(s=="any intro or no intro") return "개요 유무 무관";
  if(s=="any intro") return "개요 있음";
  if(s=="no intro") return "개요 없음";
  if(s=="intro containing...") return "개요에 다음 내용 포함...";
  if(s=="any definition or no definition") return "정의 유무 무관";
  if(s=="any definition") return "정의 있음";
  if(s=="no definition") return "정의 없음";
  if(s=="definition containing...") return "정의에 다음 내용 포함...";
  if(s=="any example or no example") return "용례 유무 무관";
  if(s=="any example") return "용례 있음";
  if(s=="no example") return "용례 없음";
  if(s=="example containing...") return "용례에 다음 내용 포함...";
  if(s=="Automatic changes") return "자동 변경";
  if(s=="NAME") return "이름";
  if(s=="BLURB") return "소개";
  if(s=="level") return "권한 수준";
  if(s=="reader") return "열람자";
  if(s=="editor") return "편집자";
  if(s=="creator") return "작성자";
  if(s=="administrator") return "관리자";
  if(s=="configurator") return "설정 관리자";
  if(s=="no change") return "변경 없음";
  if(s=="change to 'not checked'") return "'미검토'로 변경";
  if(s=="change to 'hidden'") return "'숨김'으로 변경";
  if(s=="change to 'not checked' and 'hidden'") return "'미검토' 및 '숨김'으로 변경";
  if(s=="LAST SEEN") return "최근 접속";
  if(s=="NEVER") return "접속 기록 없음";
  if(s=="No termbases") return "용어집 없음";
  if(s=="language") return "언어";
  if(s=="major") return "주요";
  if(s=="minor") return "보조";
  if(s=="role") return "역할";
  if(s=="title") return "제목";
  if(s=="ACCESS LEVEL") return "접근 권한";
  if(s=="LICENCE") return "라이선스";
  if(s=="private") return "비공개";
  if(s=="public") return "공개";
  if(s=="trigger_dateStampChange") return "날짜 변경";
  if(s=="trigger_domainAdd") return "분야 추가";
  if(s=="trigger_domainRemove") return "분야 제거";
  if(s=="trigger_domainReorder") return "분야 순서 변경";
  if(s=="trigger_domainChange") return "분야 변경";
  if(s=="trigger_desigAdd") return "용어 추가";
  if(s=="trigger_desigRemove") return "용어 제거";
  if(s=="trigger_desigReorder") return "용어 순서 변경";
  if(s=="trigger_desigClarifChange") return "보충 설명 변경";
  if(s=="trigger_desigAcceptChange") return "사용 적합성 변경";
  if(s=="trigger_termLangChange") return "용어 언어 변경";
  if(s=="trigger_termWordingChange") return "용어 표기 변경";
  if(s=="trigger_termInflectAdd") return "굴절형 추가";
  if(s=="trigger_termInflectRemove") return "굴절형 제거";
  if(s=="trigger_termInflectReorder") return "굴절형 순서 변경";
  if(s=="trigger_termInflectLabelChange") return "굴절형 레이블 변경";
  if(s=="trigger_termInflectTextChange") return "굴절형 표기 변경";
  if(s=="trigger_termAnnotAdd") return "용어 주석 추가";
  if(s=="trigger_termAnnotRemove") return "용어 주석 제거";
  if(s=="trigger_termAnnotReorder") return "용어 주석 순서 변경";
  if(s=="trigger_termAnnotPositionChange") return "용어 주석 위치 변경";
  if(s=="trigger_termAnnotLabelChange") return "용어 주석 레이블 변경";
  if(s=="trigger_introChange") return "개요 변경";
  if(s=="trigger_definitionAdd") return "정의 추가";
  if(s=="trigger_definitionRemove") return "정의 제거";
  if(s=="trigger_definitionReorder") return "정의 순서 변경";
  if(s=="trigger_definitionTextChange") return "정의 내용 변경";
  if(s=="trigger_exampleAdd") return "용례 추가";
  if(s=="trigger_exampleRemove") return "용례 제거";
  if(s=="trigger_exampleReorder") return "용례 순서 변경";
  if(s=="trigger_exampleTextAdd") return "용례 문장 추가";
  if(s=="trigger_exampleTextRemove") return "용례 문장 제거";
  if(s=="trigger_exampleTextReorder") return "용례 문장 순서 변경";
  if(s=="trigger_exampleTextChange") return "용례 문장 내용 변경";
  if(s=="trigger_collectionAdd") return "모음 추가";
  if(s=="trigger_collectionRemove") return "모음 제거";
  if(s=="trigger_collectionReorder") return "모음 순서 변경";
  if(s=="trigger_collectionChange") return "모음 변경";
  if(s=="trigger_extranetAdd") return "엑스트라넷 추가";
  if(s=="trigger_extranetRemove") return "엑스트라넷 제거";
  if(s=="trigger_extranetReorder") return "엑스트라넷 순서 변경";
  if(s=="trigger_extranetChange") return "엑스트라넷 변경";
  if(s=="trigger_sourceAdd") return "출처 추가";
  if(s=="trigger_sourceRemove") return "출처 제거";
  if(s=="trigger_sourceReorder") return "출처 순서 변경";
  if(s=="trigger_sourceChange") return "출처 변경";
  if(s=="trigger_nonessentialChange") return "필수 여부 변경";
  if(s=="(blank)") return "(빈 값)";
  if(s=="Simple Multilingual Termbase") return "기본 다국어 용어집";
  if(s=="Simple Bilingual Termbase") return "기본 이중 언어 용어집";
  if(s=="Simple Monolingual Termbase") return "기본 단일 언어 용어집";
  if(s=="Enter a human-readable title such as \"My Dictionary of Sports Terms\". You will be able to change this later.") return "\"나의 스포츠 용어 사전\"처럼 알아보기 쉬운 제목을 입력하세요. 나중에 변경할 수 있습니다.";
  if(s=="This will be your termbase's address on the web. You will be able to change this later.") return "용어집의 웹 주소로 사용됩니다. 나중에 변경할 수 있습니다.";
  if(s=="You can choose a template here to start you off. Each template comes with a few sample entries. You will be able to change or delete those and to customize the template.") return "시작할 때 사용할 템플릿을 선택하세요. 각 템플릿에는 예시 항목이 몇 개 들어 있습니다. 예시 항목을 수정하거나 삭제하고, 템플릿을 원하는 대로 바꿀 수 있습니다.";
  if(s=="Your termbase is ready.") return "용어집이 준비되었습니다.";
  if(s=="TERM OF THE DAY") return "오늘의 용어";
  if(s=="set to next available date") return "다음으로 지정 가능한 날짜로 설정";
  if(s=="Display from") return "표시 시작일";
  if(s=="Display until") return "표시 종료일";
  if(s=="News and announcements") return "소식 및 공지사항";
  if(s=="Create your account") return "계정 만들기";
  if(s=="Reset your password") return "비밀번호 재설정";
  if(s=="Terminologue signup") return "Terminologue 회원 가입";
  if(s=="Please follow the link below to create your Terminologue account:") return "아래 링크를 클릭하여 Terminologue 계정을 만드세요:";
  if(s=="Terminologue password reset") return "Terminologue 비밀번호 재설정";
  if(s=="Please follow the link below to reset your Terminologue password:") return "아래 링크를 클릭하여 Terminologue 비밀번호를 재설정하세요:";
  if(s=="This page is only available in English.") return "이 페이지는 영어로만 제공됩니다.";
  if(s=="DRAFTING STATUS") return "작성 상태";
  if(s=="draft entry") return "초안 항목";
  if(s=="finished entry") return "작성 완료 항목";
  if(s=="DRAFT") return "초안";
  if(s=="FINISHED") return "작성 완료";
  if(s=="any drafting status") return "모든 작성 상태";
  if(s=="Prefabricated comments") return "미리 정의된 댓글";
  if(s=="NOTES") return "비고";
  if(s=="note") return "비고";
  if(s=="NOT") return "비고";
  if(s=="with or without notes") return "비고 유무 무관";
  if(s=="with a note") return "비고 있음";
  if(s=="with a note containing...") return "비고에 다음 내용 포함...";
  if(s=="without notes") return "비고 없음";
  if(s=="any type") return "모든 유형";
  if(s=="private note, not shown on extranets") return "비공개 비고, 엑스트라넷에 표시하지 않음";
  if(s=="private note, shown on extranets") return "비공개 비고, 엑스트라넷에 표시";
  if(s=="public note") return "공개 비고";
  if(s=="Note types") return "비고 유형";
  if(s=="LEVEL") return "공개 범위";
  if(s=="with a comment") return "댓글 있음";
  if(s=="with a comment containing...") return "댓글에 다음 내용 포함...";
  if(s=="TBX export") return "TBX 내보내기";
  if(s=="TBX import") return "TBX 가져오기";
  if(s=="Empty the termbase") return "용어집 비우기";
  if(s=="Careful now! You are about to delete this termbase. You will not be able to undo this.") return "주의! 이 용어집을 삭제하려고 합니다. 이 작업은 되돌릴 수 없습니다.";
  if(s=="Careful now! You are about to delete all entries and their history. You will not be able to undo this.") return "주의! 모든 항목과 변경 이력을 삭제하려고 합니다. 이 작업은 되돌릴 수 없습니다.";
  if(s=="RELATED TERMS") return "관련 용어";
  if(s=="Your termbase at a glance") return "용어집 한눈에 보기";
  if(s=="Number of entries") return "항목 수";
  if(s=="Number of items in history log") return "변경 이력 수";
  if(s=="Your termbase is stored in the file %F") return "용어집이 저장된 파일: %F";
  if(s=="File size") return "파일 크기";
  if(s=="Download %F") return "%F 다운로드";
  if(s=="Upload %F") return "%F 업로드";
  if(s=="Make sure that the file you are uploading is a valid Terminologue termbase. If you upload something else you will do irreparable damage to your termbase.") return "업로드할 파일이 올바른 Terminologue 용어집 파일인지 확인하세요. 다른 파일을 업로드하면 용어집이 복구할 수 없을 정도로 손상됩니다.";
  if(s=="PARENT") return "상위 분야";
  if(s=="no parent") return "상위 분야 없음";
  if(s=="excluding subdomains") return "하위 분야 제외";
  if(s=="including subdomains") return "하위 분야 포함";
  if(s=="the entry has this domain") return "이 분야가 지정된 항목";
  if(s=="the entry has only this domain") return "이 분야만 지정된 항목";
  if(s=="the entry has not only this domain") return "이 분야와 다른 분야도 지정된 항목";
  if(s=="Careful! If you remove yourself from this termbase you will lose access to it.") return "주의! 이 용어집에서 자신을 제거하면 용어집에 접근할 수 없게 됩니다.";
  if(s=="Leave this termbase") return "용어집에서 나가기";
  if(s=="IMG") return "이미지";
  if(s=="IMAGES") return "이미지";
  if(s=="image") return "이미지";
  if(s=="credits") return "저작자 표시";
  if(s=="link to source") return "출처 링크";
  if(s=="The file is too large. The maximum allowed size is $1 bytes.") return "파일이 너무 큽니다. 최대 허용 크기는 $1바이트입니다.";

  if(!gloss) console.log(`if(s=="${s}") return "";`);
  else console.log(`if(s=="${s}", "${gloss}") return "";`);
  //if(s=="") return s;
  return s;
}

try {
  module.exports={
    L: L,
  }
} catch(e){}
